## creation
## accesing and slicing
## attributes and methods
## operations

In [2]:
list = range(1,11)
list

range(1, 11)

In [3]:
# import numpy
import numpy as np

In [4]:
array = np.array(list)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#create an array from tuple
tuple=range(1,21)
tuple

range(1, 21)

In [8]:
array=np.array(tuple)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## methods for creation an array

arange()
linspace()
zeros
eye
ones
etc

**'np.linspace(start,end,num)'**

In [8]:
array=np.linspace(1,10,15)
array

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [9]:
array =np.linspace(5,14,25)
array

array([ 5.   ,  5.375,  5.75 ,  6.125,  6.5  ,  6.875,  7.25 ,  7.625,
        8.   ,  8.375,  8.75 ,  9.125,  9.5  ,  9.875, 10.25 , 10.625,
       11.   , 11.375, 11.75 , 12.125, 12.5  , 12.875, 13.25 , 13.625,
       14.   ])

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(2)

array([1., 1.])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [24]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## random number generation

In [26]:
array = np.random.rand(2) #[0,1) #uniform distribution
array

array([0.85195811, 0.90675933])

In [27]:
array=np.random.rand(3,4)

In [28]:
array

array([[0.97208998, 0.80651743, 0.83715962, 0.41460145],
       [0.31961119, 0.19119562, 0.4553931 , 0.09246812],
       [0.62821483, 0.27273939, 0.32714218, 0.94418547]])

mean =0 varaiance=1 for standard normal distribution

In [31]:
array =np.random.randn(2)
array

array([1.27330477, 1.28315599])

In [32]:
array=np.random.randn(3,4)
array

array([[-0.59492136, -0.66835178,  0.58853833, -0.26436844],
       [ 1.77986118, -2.01932757,  0.827027  , -1.01405958],
       [-0.83944619,  1.80801756,  0.23028961, -1.84579502]])

# create an array of random integer from 1 to 20 with suitable order

### attributes

In [34]:
array=np.array([2,3,4,5,7])

In [35]:
array

array([2, 3, 4, 5, 7])

In [36]:
array.shape

(5,)

In [37]:
array.dtype

dtype('int32')

In [38]:
array.ndim

1

In [40]:
array.size

5

In [9]:
array=np.linspace([2,3,4,5],[2,3,4,6],[3,4,5,6])

TypeError: 'function' object is not subscriptable

In [45]:
array.shape

(4,)

In [48]:
array=np.random.rand(3,4)

In [49]:
array.dtype

dtype('float64')

In [50]:
array.size

12

## indexing : selection based on index  

### one dimesnional array  

In [56]:
## array[index] :for single value selection      

In [57]:
array=np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array[5]

6.875

In [15]:
array[[2,3,7,6]]

array([5.75 , 6.125, 7.625, 7.25 ])

#### two diemnsional array  

In [64]:
array=np.arange(1,10)

In [65]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
array.shape=(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array[ row_ind , col_ind]

In [68]:
array[2,1]

8

In [69]:
array[1,2]

6

In [70]:
array=np.linspace(1,20,15)
array

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])

In [71]:
array.shape=(5,3)

In [72]:
array

array([[ 1.        ,  2.35714286,  3.71428571],
       [ 5.07142857,  6.42857143,  7.78571429],
       [ 9.14285714, 10.5       , 11.85714286],
       [13.21428571, 14.57142857, 15.92857143],
       [17.28571429, 18.64285714, 20.        ]])

In [73]:
array[3,1]

14.571428571428573

In [74]:
array[4,2]

20.0

In [75]:
array[2,2]

11.857142857142858

In [76]:
array[2][2]

11.857142857142858

In [77]:
list=[[[2,3,4,5],[7,8,9,6],[14,21,57,60]]]

In [78]:
array=np.array(list)
array

array([[[ 2,  3,  4,  5],
        [ 7,  8,  9,  6],
        [14, 21, 57, 60]]])

In [80]:
array[0][1,2]

9

In [81]:
array[0][1][2]

9